# Generated by Django 4.2.23 on 2025-07-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('sticker_type', models.PositiveSmallIntegerField(choices=[(1, '조금 더 노력해봐요'), (2, '잘하고 있어요'), (3, '참 잘했어요'), (4, '아주 훌륭해요'), (5, '정말 최고예요')])),
                ('message', models.CharField(blank=True, max_length=255)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_calendars', to='child_users.childuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
