# Generated by Django 4.2.21 on 2025-07-06 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('avatarUrl', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('order_level', models.PositiveSmallIntegerField(default=0)),
                ('manners_level', models.PositiveSmallIntegerField(default=0)),
                ('selfcare_level', models.PositiveSmallIntegerField(default=0)),
                ('clean_level', models.PositiveSmallIntegerField(default=0)),
                ('calm_level', models.PositiveSmallIntegerField(default=0)),
                ('kindness_level', models.PositiveSmallIntegerField(default=0)),
                ('saving_level', models.PositiveSmallIntegerField(default=0)),
                ('eating_level', models.PositiveSmallIntegerField(default=0)),
                ('average_level', models.FloatField(default=0.0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
